services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: nba-backend
    ports:
      - "5200:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: